models = [
    {id: 'gemini-flashV2', 'nombre': 'Gemini Flash V2'},
    {id: 'gemini-2.0-flash', 'nombre': 'Gemini 2.0 Flash'},
    {id: 'gemini-2.5-flash-preview-05-20', 'nombre': 'Gemini 2.5 Flash'},
    {id: 'gemini-2.0-flash-lite', 'nombre': 'Gemini 2.0 Flash-Lite'},
    {id: 'gemma-3-27b-it', 'nombre': 'Gemma 3'},
    {id: 'gemma-3n-e4b-it', 'nombre': 'Gemma 3n'},
    {id: 'gemini-1.5-flash', 'nombre': 'Gemini 1.5 Flash'},
    {id: 'gemini-1.5-flash-8b', 'nombre': 'Gemini 1.5 Flash-8B'},
    {id: 'gemini-1.5-pro', 'nombre': 'Gemini 1.5 Pro'},
    {id: 'embedding-gecko-001', 'nombre': 'Embedding Gecko'},
    {id: 'gemini-1.0-pro-vision-latest', 'nombre': 'Gemini 1.0 Pro Vision'},
    {id: 'gemini-pro-vision', 'nombre': 'Gemini 1.0 Pro Vision'},
    {id: 'gemini-1.5-pro-latest', 'nombre': 'Gemini 1.5 Pro Latest'},
    {id: 'gemini-1.5-pro-001', 'nombre': 'Gemini 1.5 Pro 001'},
    {id: 'gemini-1.5-pro-002', 'nombre': 'Gemini 1.5 Pro 002'},
    {id: 'gemini-1.5-flash-latest', 'nombre': 'Gemini 1.5 Flash Latest'},
    {id: 'gemini-1.5-flash-001', 'nombre': 'Gemini 1.5 Flash 001'},
    {id: 'gemini-1.5-flash-8b', 'nombre': 'Gemini 1.5 Flash-8B'},
    {id: 'gemini-1.5-flash-8b-001', 'nombre': 'Gemini 1.5 Flash-8B 001'},
    {id: 'gemini-1.5-flash-8b-latest', 'nombre': 'Gemini 1.5 Flash-8B Latest'},
    {id: 'gemini-1.5-flash-8b-exp-0827', 'nombre': 'Gemini 1.5 Flash 8B Experimental 0827'},
    {id: 'gemini-1.5-flash-8b-exp-0924', 'nombre': 'Gemini 1.5 Flash 8B Experimental 0924'},
    {id: 'gemini-2.5-pro-exp-03-25', 'nombre': 'Gemini 2.5 Pro Experimental 03-25'},
    {id: 'gemini-2.5-pro-preview-03-25', 'nombre': 'Gemini 2.5 Pro Preview 03-25'},
    {id: 'gemini-2.5-flash-preview-04-17', 'nombre': 'Gemini 2.5 Flash Preview 04-17'},
    {id: 'gemini-2.5-flash-preview-05-20', 'nombre': 'Gemini 2.5 Flash Preview 05-20'},
    {id: 'gemini-2.5-flash-preview-04-17-thinking', 'nombre': 'Gemini 2.5 Flash Preview 04-17 for cursor testing'},
    {id: 'gemini-2.5-pro-preview-05-06', 'nombre': 'Gemini 2.5 Pro Preview 05-06'},
    {id: 'gemini-2.0-flash-exp', 'nombre': 'Gemini 2.0 Flash Experimental'},
    {id: 'gemini-2.0-flash-001', 'nombre': 'Gemini 2.0 Flash 001'},
    {id: 'gemini-2.0-flash-exp-image-generation', 'nombre': 'Gemini 2.0 Flash (Image Generation) Experimental'},
    {id: 'gemini-2.0-flash-lite-001', 'nombre': 'Gemini 2.0 Flash-Lite 001'},
    {id: 'gemini-2.0-flash-lite-preview-02-05', 'nombre': 'Gemini 2.0 Flash-Lite Preview 02-05'},
    {id: 'gemini-2.0-pro-exp', 'nombre': 'Gemini 2.0 Pro Experimental'},
    {id: 'gemini-2.0-pro-exp-02-05', 'nombre': 'Gemini 2.0 Pro Experimental 02-05'},
    {id: 'gemini-exp-1206', 'nombre': 'Gemini Experimental 1206'},
    {id: 'gemini-2.0-flash-thinking-exp-01-21', 'nombre': 'Gemini 2.5 Flash Preview 04-17'},
    {id: 'gemini-2.5-flash-preview-tts', 'nombre': 'Gemini 2.5 Flash Preview TTS'},
    {id: 'gemini-2.5-pro-preview-tts', 'nombre': 'Gemini 2.5 Pro Preview TTS'},
    {id: 'learnlm-2.0-flash-experimental', 'nombre': 'LearnLM 2.0 Flash Experimental'},
    {id: 'gemma-3-1b-it', 'nombre': 'Gemma 3 1B'},
    {id: 'gemma-3-4b-it', 'nombre': 'Gemma 3 4B'},
    {id: 'gemma-3-12b-it', 'nombre': 'Gemma 3 12B'},
    {id: 'gemma-3-27b-it', 'nombre': 'Gemma 3 27B'},
    {id: 'gemma-3n-e4b-it', 'nombre': 'Gemma 3n E4B'},
    {id: 'embedding-001', 'nombre': 'Embedding 001'},
    {id: 'text-embedding-004', 'nombre': 'Text Embedding 004'},
    {id: 'gemini-embedding-exp-03-07', 'nombre': 'Gemini Embedding Experimental 03-07'},
    {id: 'gemini-embedding-exp', 'nombre': 'Gemini Embedding Experimental'}
]